Codaone/DEXBot

dexbot/storage.py
Make Storage a bit more efficient
- don't wait for results when only writing
- don't poll, use threading.Event instead
=> Optimise storage

dexbot/basestrategy.py, dexbot/controllers/create_bot_controller.py, dexbot/strategies/simple.py, dexbot/views/create_bot.py, dexbot/views/edit_bot.py, dexbot/views/ui/create_bot_window.ui, dexbot/views/ui/edit_bot_window.ui
=> Dynamic center price

.travis.yml, Makefile, appveyor.yml
Fixes related to #22 :
- Fix for osx build : https://travis-ci.org/Codaone/DEXBot/jobs/351290237
- Upload release assets when merging into master
- Appveyor build using make
=> OSX build fix & releases on master branch

dexbot/controllers/create_worker_controller.py, dexbot/strategies/relative_orders.py, dexbot/views/ui/worker_item_widget.ui
=> Change the name of simple strategy to relative orders

README.md
This should be reviewed properly once the procedure has stabilized, but for now this should suffice.
=> Removed confusing information and updated with relevant instructions

.travis.yml, LICENSE.txt, MANIFEST.in, Makefile, cli.py, cli.spec, dexbot/__init__.py, dexbot/cli.py, dexbot/controllers/main_controller.py, dexbot/gui.py, gui.spec, requirements.txt, setup.py
- Create config.yml file in user config directory if it does not exist and use that one everywhere
- Created two separate bin entrypoints for cli & gui modes: dexbot-cli & dexbot-gui
- Moved cli & gui modules inside dexbot root package
- Do UI python build via setuptools build hook , instead of install
=> Build general fixes

cli.py, dexbot/basestrategy.py, dexbot/strategies/relative_orders.py, gui.py
This fixes #81 and also fixes #73
=> Fix worker crashing when trying to cancel non-existing orders

dexbot/__init__.py, dexbot/strategies/relative_orders.py
Orders now get updated when an order is fully filled
=> Change relative orders order updating logic

dexbot/basestrategy.py, dexbot/controllers/main_controller.py
more logging for strange windows errors
and a "soft-fail" for oje graphene error in particular
=> More logging for bugs

dexbot/__init__.py, dexbot/basestrategy.py
- Change cancel order logic
- Change center price calculation logic
=> Misc fixes

dexbot/views/worker_list.py
=> Fix wrong worker limit issue #124

dexbot/__init__.py, dexbot/basestrategy.py, dexbot/controllers/strategy_controller.py, dexbot/strategies/relative_orders.py, dexbot/views/ui/create_worker_window.ui, dexbot/views/ui/edit_worker_window.ui, dexbot/views/ui/forms/relative_orders_widget.ui
Adds a setting to make center price offset optional. The setting is off by default
Resolves #130
=> Optional center offset

dexbot/__init__.py, dexbot/basestrategy.py
=>  Fix a crash when an order is filled instantly after its placement

dexbot/basestrategy.py, dexbot/controllers/main_controller.py, dexbot/strategies/relative_orders.py, dexbot/views/errors.py, dexbot/views/ui/worker_item_widget.ui, dexbot/views/worker_item.py, dexbot/views/worker_list.py, dexbot/worker.py
Each worker item gets a label a the bottom which is updated with new log entries of INFO/WARNING level for that worker.
Some new logging commands added so users get a steady stream of updates
as the worker is running,
=> a fairly basic status system. 

dexbot/strategies/staggered_orders.py
Previous staggered blockchain orders should be preserved after
restarting the worker.
=> Do not cancel all orders in place_orders()

dexbot/ui.py
=> Fix logger verbosity initialization

Makefile
Fixing my own issue in Arch Linux. Shouldn't really interfere with other OS'.
=> Fix #164 permission error as normal user

dexbot/views/layouts/flow_layout.py, dexbot/views/ui/worker_list_window.ui, dexbot/views/worker_list.py
Change current layout to fully utilize the available space for worker list redesign
Closes #181
=> Add flow layout to worker list window

.travis.yml, appveyor.yml
=> Separated CLI and GUI packages from the birany packages

dexbot/controllers/strategy_controller.py, dexbot/strategies/staggered_orders.py, dexbot/views/ui/forms/relative_orders_widget.ui, dexbot/views/ui/forms/staggered_orders_widget.ui
Add manual center price option to Staggered orders configuration #179
=> Staggered orders manual center price

dexbot/basestrategy.py
=> Fix crashing when deleting a worker

dexbot/basestrategy.py, dexbot/controllers/strategy_controller.py, dexbot/strategies/relative_orders.py, dexbot/views/ui/forms/relative_orders_widget.ui, dexbot/worker.py
Add a field to worker's options for manually setting center price offset #153
=> Add manual center price offset option

dexbot/controllers/main_controller.py, dexbot/helper.py
Moved log file to same location as the orders log
=> Change log file location

dexbot/__init__.py, dexbot/cli_conf.py, dexbot/config.py, dexbot/whiptail.py
=> Add default list of nodes

dexbot/controllers/worker_controller.py, dexbot/views/create_worker.py, dexbot/views/ui/create_worker_window.ui, dexbot/views/ui/edit_worker_window.ui, dexbot/views/ui/forms/relative_orders_widget.ui, dexbot/views/ui/forms/staggered_orders_widget.ui, dexbot/views/worker_item.py
=> Change private key input to be optional value in the GUI

dexbot/controllers/strategy_controller.py, dexbot/views/strategy_form.py
This pr will:
- Fix value fetching for auto generated ComboBox elements
- Add attribute access for auto generated ui elements
=> Auto UI generation fixes

dexbot/basestrategy.py
=> Set fee_asset to str as python-bitshares expects

dexbot/basestrategy.py
=> Do not try to buy/sell 0 amount

Makefile, appveyor.yml, dexbot/basestrategy.py, dexbot/strategies/staggered_orders.py, requirements.txt, setup.py
This pr will fix a startup crash on specific systems
And also fix a crash when creating a worker
=> Update project dependencies

dexbot/strategies/staggered_orders.py
Note that the `if not self.bootstrapping:` I'm not sure if it really works
=> Fix starting strategy on empty market with cp given

dexbot/controllers/strategy_controller.py, dexbot/views/ui/create_worker_window.ui, dexbot/views/ui/forms/relative_orders_widget.ui, dexbot/views/ui/forms/staggered_orders_widget.ui
Fixes an error when creating relative orders worker.
=> Hotfix relative orders

dexbot/strategies/base.py
I haven't tested this, but wanted to convey the principle I think works. Both quote_amount and base_amount can be passed to any of the functions, and it will either use the one specified or if both are specified then it will default to the asset that is allocated: base for buy orders and quote for sell orders. For the functions that can make use of the logic in `get_market_sell/buy_price()`, the amount arguments are passed forward as such.
This commit breaks the fetch_depth stuff within `get_market_spread()`. fetch_depth should be implemented in `get_market_sell/buy_price()`, because then it will benefit also cp and spread methods.
I hope all this makes sense. Note that it is unlikely that a strategy has any use of "depth" if it means some amount of market orders. There can be a million …
=> Makes cp and spread methods use logic of get_..._price()

README.md
Updated description with links to OSX and Raspberry pi install instructions on the Wiki
=> update to include OSX and Raspberry pi

dexbot/strategies/base.py
To migrate staggered orders to base.py, it needs changes I made into old basestrategy.
=> Changes from basestrategy

dexbot/controllers/settings_controller.py
Fixes a bug when moving node in the settings window and focus on the moved node was lost.
=> Fix setting node move

dexbot/views/ui/worker_list_window.ui, dexbot/views/worker_list.py
=> Add "Help" button which opens GitHub documentation

dexbot/views/ui/settings_window.ui
Fixes problem when changing settings window size.
=> Fix settings window scaling

dexbot/strategies/base.py
I'm not sure if the second exeption should include a return statement. Please check logic
=> added some missing return statements

dexbot/controllers/worker_controller.py
There's no reason not to allow trading with owner key. I also  had the problem where a private key was active and owner, and this should solve it.
=> allowed also owner key for workers

dexbot/strategies/base.py
=> Avoid passing None to get_updated_limit_order

setup.py
Update pybitshares to version 0.2.0 closes #335
Also updates python-graphenelib which fixes #312
=> Bitshares update 0.2.0

.travis.yml
=> Fix OSX build not compiling with Travis

dexbot/views/worker_list.py
=> Fix adding twice to num_of_workers

dexbot/strategies/relative_orders.py, dexbot/worker.py
- Fix errors when using dynamic spread or dynamic centre price on an empty market
- Fix case where editing paused worker pauses another worker with same strategy
=> Small fixes to Relative Orders and worker editing

dexbot/cli_conf.py
=> Fix CLI configure saving right parameters

setup.py
Updates following dependencies:
python-bitshares 0.2.0 => 0.2.1
uptick 0.1.9 => 0.2.0 
Closes #375
=> Update uptick to 0.2.0 and bitshares to 0.2.1

dexbot/controllers/worker_controller.py
=> Private key exception when creating a worker

dexbot/worker.py
=> Fix exiting after signal

dexbot/strategies/base.py, dexbot/strategies/staggered_orders.py
=>  Migrate staggered orders to base.py, other minor changes

dexbot/strategies/staggered_orders.py
=> Fixes for Staggered Orders

.travis.yml, appveyor.yml, requirements.txt, setup.py
Updates project dependencies to new version numbers
- aiohttp 3.0.1
- pyqt5 5.11.3
- pyinstaller 3.4
- websocket-client 0.54.0
=> Update aiohttp to 3.0.1

dexbot/worker.py
=> Fix error when trying to delete worker from GUI

dexbot/strategies/base.py
=> Emit a log message when fee asset balance is too small

requirements.txt, setup.py
move setup.py packages to requirements.txt so all in one file
=> 460 project dependences merge

dexbot/strategies/base.py
=> Prevent ZeroDivisionError in update_gui_profit()

dexbot/strategies/base.py
=> Fix division by zero in get_market_xxx_price

dexbot/strategies/staggered_orders.py
=> Handle trx broadcasting errors in replace_virtual_order_with_real()

dexbot/strategies/staggered_orders.py
=> Enforce `spread > increment` check

dexbot/strategies/base.py
cancel_orders() should return True only when cancel was success.
Closes: #467
=> Refactor cancel_orders()

dexbot/__init__.py, dexbot/strategies/base.py
#470 edit display for end user so it reads QUOTE/BASE instead of BASE/QUOTE
=> issue 470 market setting

dexbot/strategies/staggered_orders.py
=> Fix exception logging

dexbot/strategies/staggered_orders.py
If order was filled partially it may stay as a dust order.
Instead of waiting until it will be fully filled, just cancel it and use
obtained funds to place closer order on opposite side.
Closes: #432
=> Introduce dust orders handling

dexbot/strategies/base.py, dexbot/strategies/staggered_orders.py
=> Fix conditional expressions logic

dexbot/cli_conf.py, dexbot/config_validator.py, requirements.txt
Version upgrade + switch to own forks.
=> 570 pybitshares 0.3.x

dexbot/orderengines/bitshares_engine.py, dexbot/strategies/base.py, dexbot/strategies/relative_orders.py
Closes #593 
new write_order_log version to be written in the future.
=> #593 move orders log to base.py and remove reference to write_order_log in RO

dexbot/strategies/staggered_orders.py, tests/strategies/staggered_orders/test_staggered_orders_complex.py
Fix #587 and another race when replacing real -> virtual order (see commits)
=> Fix several race conditions in SO

dexbot/ui.py
Logging level was not being set on "dexbot" logger.
=> Set loglevel on "dexbot" logger

dexbot/cli.py, dexbot/cli_conf.py
=>  add delete node option to cli configure menu

dexbot/ui.py
=> Change string formating to use format() instead of f-string

.travis.yml, dexbot/strategies/king_of_the_hill.py, requirements-dev.txt, tests/README.md, tests/conftest.py, tests/migrations/test_migrations.py, tests/node_config/config.ini, tests/storage/test_storage.py, tests/strategies/king_of_the_hill/conftest.py, tests/strategies/king_of_the_hill/test_king_of_the_hill.py, tests/test_measure_latency.py, tests/test_worker_infrastructure.py
Apply this PR after #663 
Closes #668 
Closes #670
=> Fixes for KOTH

dexbot/strategies/staggered_orders.py
Order price is now more precise according to actual asset precisions.
Closes: #642
=> Recalculate price for virtual orders

dexbot/strategies/staggered_orders.py, tests/strategies/staggered_orders/test_staggered_orders_complex.py
A slight regression was introduced in 32dbafbcace9d1113578416cc24041d75eea3741
=> Fix cancel dust order

requirements.txt
See https://github.com/websocket-client/websocket-client/issues/449
Closes: #594
=> Fix clean exit from cli
