Codaone/DEXBot

dexbot/bot.py

this is a very simple change to allow easy access to user-written bots.
the original stakemachine only lets you load bots accessible from the standard sys.path
which makes it tricky to load your own bot: you would have to set PYTHONPATH before doing 'dexbot run'
this is a pure convience feature to add ~/bots to sys.path if it exists.
no change in behaviour if users have no such directory.

allow users to optionally have a ~/bots directory for their own bots.

---

dexbot/basestrategy.py
dexbot/bot.py
dexbot/strategies/echo.py
dexbot/strategies/walls.py
dexbot/ui.py

each bot instance gets its own LoggerAdapter (same interface as standard Python Logger)
difference is basestrategy adds appropriate bot metadata (bot name, market, account and disabled status) to each log entry through the "extra" field.
ui.py is updated so text logs have this information. also date information is suppressed when using systemd (as journald will add it for us)
but main point is for GUI code to tap the stream of log entries using
getLogger('dexbot.bot.per_bot') and display the log in an interesting way (per bot log window, colour-coded, etc)

embellishments to the logging system

---

dexbot/bot.py

With my follow orders bot, it establishes the first orders during its __init__() method.
This cna be quite slow (tens of seconds) if there are many orders. Currently this would be executed in BotInfrastructure.__init__, potentially in the main thread.
The slow parts of initialisation are now spun out into init_bots, called from BotInfrastructure.run(), so this will naturally occur in the background thread.

Fast bot init

---

dexbot/bot.py
dexbot/cli.py

Allows clean exit when receives the classic UNIX signals (SIGINT, SIGTERM, SIGHUP)
Will work limited extent on Windows too. (Control-C will work, not much else)
Exit is 'clean' in the sense that it waits until the next bitshares block before exiting, bots are not interrupted in the middle of submitting orders.
Future scope to do something useful on SIGUSR1 / SIGUSR2

UNIX signal handling

---

dexbot/cli.py

to an external files
when running the CLI dexbot as a daemon, this is necessary for some management systems.

Write PID of the process

---

config.yml
dexbot/__init__.py
dexbot/views/worker_item.py

Fixes a crash in GUI when renaming a worker
Also removes the unused config.yml from the project root

Fix worker rename

---

dexbot/controllers/main_controller.py
dexbot/ui.py
dexbot/views/create_wallet.py
dexbot/views/create_worker.py
dexbot/views/edit_worker.py
dexbot/views/errors.py
dexbot/views/unlock_wallet.py
dexbot/views/worker_item.py
dexbot/views/worker_list.py

addressed issue #36 with the standard QMessageBox displayed whenver an exception happened, teither in GUI code or in the worker layer.
The full python stacktrace is available as "Details" in the Qt dialog.
Provision for adding comments to some of the more cryptic graphene eror messages (intended for where the user can fix, such as insufficient account funds or broken Internet connection)

Errordialog

---

dexbot/basestrategy.py
dexbot/ui.py

which usually represents the node being unable to sync the blockchain
do a number of retries
and display an explanation on the GUI

detect the graphene error "Assert Exception: now <= trx.expiration"

---

dexbot/strategies/relative_orders.py

With this fix, buy and sell orders should be placed at exactly the same price points regardless of which way the market is looked at. That is, the prices should be the same when:
1. Prices are calculated and market flipped upside-down, and 
2. Market is flipped first, and then prices calculated.
This fix reduces the slight bias towards selling. It also makes huge spread's calculation work better.

Improve Relative Orders spread calculation

---

dexbot/strategies/staggered_orders.py

Prevent double removal in staggered strategy

---

dexbot/basestrategy.py
dexbot/cli.py
dexbot/controllers/main_controller.py
dexbot/strategies/staggered_orders.py
dexbot/views/worker_item.py
dexbot/worker.py

Actual behavior
===========
In the staggered orders strategy we have a following logic at the initialization:
```python
if self['setup_done']:
self.place_orders()
else:
self.init_strategy()
```
By this logic a fresh worker will do `self.init_strategy()`. It will:
1. Create a market orders
2. Save orders to the database
Next, we're stopped worker and let it be offline. During this time some orders will be filled.
Next, we're starting worker again. This time `self.place_orders()` will be executed. This means **bot will  place already filled orders again** likely causing an error `Insufficient buy/sell balance`:
```python
def place_orders(self):
""" Place all the orders found in the database
"""
orders = self.fetch_orders()
for order_id, order in orders.items():
if not …
```

Fix logic in staggered orders maintenance

---

dexbot/strategies/staggered_orders.py

Orders should not be cancelled on error because on next run reverse
orders will be placed effectively selling all your funds.
Closes: #170

Do not cancel orders on error for staggered strategy

---

dexbot/basestrategy.py
dexbot/strategies/staggered_orders.py

By default, dexbot uses python-bitshares order expiration time (7 days)
which is quite low for staggered orders. Whether order expired, on the
next run of the staggered orders worker it will treat expired order as
filled and so a reverse order will be placed, effectively selling your
funds (same as #170).
Closes: #174

Set high order expiration time for staggered orders

---

dexbot/strategies/staggered_orders.py

On every market update we're getting an event in on_market() callback
inside worker.py which leads to calling
self.workers[worker_name].onMarketUpdate(data) which then calls
Strategy.check_orders() while using staggered oders. This leads to
querying bitshares for each placed order every time market update comes
which may take 3-4 seconds!!!
On active market there are lots of market changes constantly, so the bot
parses new notifications too slow! He just always stays beyond the
actual market. In the active markets like BTS/USD there are lots of
orders happening, but the bot is able to parse only one in 3-4 seconds
(depending on number of orders and lag to the node).
As a quick solution, just limit orders checking rate to once per 5
seconds.
Closes: #169

Do not allow too often orders checking in staggered orders

---

dexbot/basestrategy.py
dexbot/cli.py
dexbot/cli_conf.py
dexbot/controllers/main_controller.py
dexbot/views/worker_item.py
dexbot/worker.py

Fix problem where old private key was not deleted and caused an error when adding new worker. Also fixed wallet locked error. Closes #210

Fix duplicate private key error

---

dexbot/basestrategy.py

I forgot asset names have dots, like `OPEN.BTC` Several people on telegram have complained the CLI installer won't let them create workers for these assets as the name can't pass the regular expression.

asset names can have dots

---

dexbot/ui.py

Fixes exceptions during handling on_market callbacks.

Pass num_retries to bitshares instance for cli

---

.travis.yml
appveyor.yml

Since _nobody_ uses the compiled CLI files, it's better to remove the compiling to speed up travis and appveyor run speed

Remove CLI compiling from releases

---

dexbot/cli_conf.py
dexbot/controllers/worker_controller.py
dexbot/helper.py
dexbot/views/strategy_form.py

this allows strategies to be published in external packages and made available via `pip` 
these can then be found and presented to the user during configuration

use pkg_resources to allow auto-discovery of third-party strategies

---

dexbot/controllers/strategy_controller.py
dexbot/strategies/relative_orders.py

- Always reset orders whether it was a filled, expired or manually
cancelled order detected
- Reset on partial fill (with % threshold, optional)
- Allow to define custom order expiration time
- Reset orders on market trade (optional)
- Reset orders on center price change threshold (optional)
- Also disable log message about correct orders to remove log noise
- Writing of a trade log entry is disabled because we cannot properly
distinguish an expired order from a filled one
Closes: #226, #270

Implement different triggers to reset orders

---

dexbot/cli_conf.py

When editing a worker Basestrategy reads worker config but it used
default config path. Fix this by passing correct config path.

Preserve --configfile when running `cli.py configure`

---

dexbot/__init__.py
dexbot/cli_conf.py
dexbot/controllers/worker_controller.py
dexbot/helper.py
dexbot/strategies/base.py
dexbot/strategies/echo.py
dexbot/strategies/relative_orders.py
dexbot/strategies/strategy_template.py
dexbot/worker.py
docs/strategybase.rst

Improved base for strategies, which replaces the old _basestrategy.py_ with new _base.py_. Strategies using the old BaseStrategy still work. BaseStrategy deprecates at some point, but for now it is recommended to move using the new StrategyBase class.
Also included is a template strategy with documentation.
Close #298

Basestrategy rework

---

dexbot/strategies/base.py

Own spread calculation was wrong and get_highest_own_buy() lacked the word "order"

two small fixes

---

setup.py

Adds websocket-client version 0.48.0 to the requirements.

websocket-client version 0.48.0

---

dexbot/cli.py

dexbot-cli --systemd run was not running the cli as a service so i added a new command runservice.
It use the cli_conf.py to generate the service file if not present.
=> dexbot-cli runservice

Added runservice to run dexbot-cli as a service: dexbot-cli runservice

---

dexbot/strategies/staggered_orders.py

The error occured when bootstrap was turned off but there is no opposite
orders. Add check for such situation.

Fix 'NoneType' in allocate_asset()

---

dexbot/ui.py

When there is no configfile, just auto-generate it at ask user to re-run
configure command.
Closes: #274

Fix dexbot-cli configure with empty config

---

setup.py

File "/home/vvk/devel/DEXBot/venv/lib/python3.6/site-packages/uptick-0.2.0-py3.6.egg/uptick/ui.py", line 7, in <module>
from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
Closes: #431

Bump uptick version to fix tabulate issue

---

dexbot/strategies/base.py

Because issue #367 is not reproducible, add order_id logging for the
possible future occurencies of this bug.
Closes: #367

Log order id in case of Exception in get_order()

---

dexbot/strategies/relative_orders.py

When using relative order amount, we need to make sure either BASE or
QUOTE amount will not be less than minimal possible amount of both
assets. Minimal possible amount is based on asset precision. E.g., for
Bitcoin minimal amount is 0.00000001 (precision = 8).
Closes: #276

Check for minimal order amount in RO

---

dexbot/strategies/base.py

Market fee calculation was broken because get_market_fee() returned a
market fee for self.fee_asset. Because get_market_fee() didn't used
anywhere except get_market_xxx_price(), just remove it.
Closes: #453

Fix market fee in get_market_xxx_price()

---

dexbot/strategies/base.py

Allow numeric in asset names during configuration. Previously config threw an error when numbers were included.  #469

#469 allow numeric in asset names

---

dexbot/cli_conf.py
dexbot/ui.py
dexbot/views/ui/create_wallet_window.ui
dexbot/views/ui/unlock_wallet_window.ui

For end user clarification, indicate that the password to be created is for uptick wallet.

add uptick description to wallet password create for cli and .ui

---

dexbot/whiptail.py

If allowed input is in range 1-5 and user entered 6 or more, treat this
as 5.
Closes: #445

Prevent exiting from list lenght bound in whiptail menu

---

dexbot/cli.py
dexbot/cli_conf.py
dexbot/cli_helper.py
dexbot/strategies/base.py
dexbot/strategies/base_config.py
dexbot/strategies/relative_config.py
dexbot/strategies/relative_orders.py
dexbot/strategies/staggered_config.py
dexbot/strategies/staggered_orders.py
dexbot/strategies/strategy_config.py
dexbot/strategies/strategy_template.py
dexbot/ui.py

this is a cli-configure refactor. pulling to codaone 458-refactor-cli so vvk can debug. Feel free to make any changes as needed you do not need my permission.
** New Menu Item Features**
- List Workers: This is a new menu item. It also allows the user to view config details. 
- For Add New Worker - WIF key added, worker name cannot be blank, account name cannot be blank
- For Editing Worker - you can change the account, as was before. However, the WIF cannot be edited. This mirrors GUI behavior. 
- Add Node: allows user to enter new node to the top of heap 
- Add Bitshares Account
- Show Bitshares Accounts that have already been added
- Help link
- Add Node
**Refactoring:** 
-  Add Config Helper class, handles most of the logic for account validation
-  ConfigElements and Config Details …

458 refactor cli configure

---

dexbot/controllers/strategy_controller.py

Uncheck reset_on_price_change when center_price_dynamic set to False.
This prevents setting of bad options combination, thus avoiding further
error.

Auto-uncheck reset_on_price_change

---

dexbot/strategies/relative_orders.py

The default value `none` should not be used for external feeds as it is no longer an option in the EXCHANGES array.  the solution is to make `gecko` the default option. Also have reordered ConfigElement to make logical sense during whiptail config.

Change external price feed options order in CLI configuration

---

dexbot/strategies/staggered_orders.py

On the sell side, don't cancel furthest orders ever, instead just place
closer sell order using available (not allocated) funds.
If target spread still not reached, cancel furthest buy side order.
Closes: #443

Simplify fallback logic

---

dexbot/strategies/base.py

When returning an order, invert() must be called not only when
deleted order is reconstructed, but in normal case too.

Fix .invert() consistency in place_market_sell_order()

---

requirements.txt

Bumping up the required version number for pybitshares to 0.3.0

Update pybitshares to version 0.3.0

---

dexbot/strategies/config_parts/base_config.py
dexbot/strategies/config_parts/relative_config.py
dexbot/strategies/config_parts/staggered_config.py
dexbot/strategies/config_parts/strategy_config.py

Fixes an error reportedly on Windows and Linux when installing DEXBot.
`ModuleNotFoundError: No module named 'dexbot.strategies.config_parts'` was caused by missing `__init__.py` from `config_part` package.

Fix installation ModuleNotFoundError

---

dexbot/strategies/base.py
dexbot/strategies/relative_orders.py

as part of refactor, we move get_external_market_center_price from base to relative orders strategy, as it is only used by RO right now, not all strategies

move get_external_market_center_price from base to relative orders

---

dexbot/ui.py

In b3e8ff104abbf3804dee761a0508f6c1a86c7816 default logfile was changed
to the same directory where the cli executable is. This is a wrong
approach as dexbot can be installed in multiple ways. System-wide
install will put the binary into /usr/bin/dexbot-cli. Applicateion must
not try to log into /usr/bin/.
This change makes logging consistent with GUI, which stores the log into
user data directory, like ~/.local/share/dexbot/dexbot.log
Closes: #490, #540

Change default logfile path for cli

---

dexbot/strategies/base.py
dexbot/strategies/staggered_orders.py

556 557 lost bitshares instance

---

Dockerfile

Now we have git+https:// in requirements.txt, so need to have git.
Closes: #599

Add git as dependency in Dockerfile

---

requirements.txt

update websocket-client to 0.56 to be compatible with graphenelib 1.1.18 requirement
https://t.me/DEXBOTbts/31269

Requirements.txt update

---

dexbot/strategies/config_parts/relative_config.py

select_choice() expect to see only "tag" as default, not ("tag", "value") tuple
Closes: #605

Fix default value supplied for cli configure

---

dexbot/orderengines/bitshares_engine.py
dexbot/pricefeeds/bitshares_feed.py
dexbot/strategies/base.py

596 bitshares attributes

---

README.md
dexbot/ui.py

This allows using DEXBot in Docker Swarm more securely using Docker secrets.
In order to try this out, simply create a file `passphrase.secret` containing the passphrase, then use the following `docker-compose.yml`
```
version: '3.6'
services:
dexbot:
build: .
networks:
- develop
volumes:
- ./dexbot-data:/home/dexbot/.local/share
- ./dexbot-config:/home/dexbot/.config/dexbot
environment:
UNLOCK: "/run/secrets/passphrase"
secrets:
- passphrase
command: dexbot-cli run
secrets:
passphrase:
file: ./passphrase.secret
networks:
develop:
driver: bridge
```

Unlocking the wallet with a Docker secret

---

cli.spec
gui.spec

Fix the problem on Windows not being able to load the KOTH strategy.
Tested as working solution from Appveyor artifacts.

Add missing hidden imports

---

Dockerfile

Quick fix for docker image on `0.15.5` release to avoid error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'ping': 'ping'
```
Closes #664

[#664] Add ping into image, as it's required for node checks

---

dexbot/orderengines/bitshares_engine.py
dexbot/pricefeeds/bitshares_feed.py
dexbot/strategies/base.py
dexbot/worker.py

#596 Properties fix

---

dexbot/strategies/relative_orders.py
tests/strategies/relative_orders/conftest.py
tests/strategies/relative_orders/test_relative_orders.py

Add an explicit check if trade belongs to current market. This fixes a
situation when account is used by multiple workers with asset
intersections. Thus a wrong trade (from different market) may be used
resulting in incirrect price and further trades.

Fix getting last own trade price in RO

---

dexbot/strategies/staggered_orders.py

A rare race condition could occur when increasing an order and replacing
same order as partially filled.

Fix race condition in SO

---

requirements.txt

Requests must be locked to 2.21 in order to prevent conflict with graphene and uptick. 
Uptick must be upgraded to 0.2.4 in order for commands such as uptick commands such as `listaccounts` and `--version` to work without throwing errors. 
Order of install:  1. requests 2. graphenelib 3. bitshares 4. uptick. 
requests==2.21.0
uptick==0.2.4
$ uptick --version 
+-------------+---------+
| name        | version |
+-------------+---------+
| uptick      | 0.2.4   |
| bitshares   | 0.3.2   |
| graphenelib | 1.1.18  |
+-------------+---------+

fix requirements so compatible with graphene and uptick

---

dexbot/cli.py
dexbot/ui.py

provide option on dexbot-cli to reset node list to default. Can be reset to general list, and also can be used with sort option, e.g. ``` dexbot-cli -s 2 resetnodes```

Nodelist reset

---

dexbot/cli.py
dexbot/node_manager.py
dexbot/ui.py

- Added option to allow user to cancel all market orders for account on dexbot-cli . 
- Todo: Option should be added to to dexbot-gui (for joelvai)
- Also corrected host_ip from 8.8.8.8 to 1.1.1.1, in cases where prior maybe blocked, latter better choice.

add cancel all market orders option to cli. change host_ip 

---

dexbot/cli_conf.py
dexbot/config_validator.py
dexbot/controllers/worker_controller.py

Now ConfigValidator doesn't have to instantiate config on its own, so it
doesn't looses custom config.
Closes: #631

Require config instance in ConfigValidator

---

dexbot/strategies/king_of_the_hill.py
tests/strategies/king_of_the_hill/test_king_of_the_hill.py

To not scary user when some asset has 0 balance in "both" mode, change
log message level to debug.
Despite report, such condition doesn't leads to "worker disabled" error.
Closes: #715

Adjust 0 balance message in "both" mode

---

dexbot/strategies/staggered_orders.py
tests/strategies/staggered_orders/test_staggered_orders_highlevel.py

Case happens when base or quote balance is not enough to place minimum
allowed order when placing lowest buy or highest sell order.
Closes: #765

Fix insufficient balance error
